In [72]:
import pandas as pd 

df = pd.read_csv("gurugram_train.csv")
df.drop(columns="Unnamed: 9",inplace=True)
df
df['Rate per sqft'] = (
    df['Rate per sqft']
    .astype(str)
    .str.replace(',', '', regex=True)
    .str.strip()
    .astype(float)
)
from sklearn.linear_model import LinearRegression

x= df.iloc[:,1]
y = df.iloc[:,2:]
clf = LinearRegression()
clf.fit(x,y)

,Area,Price,BHK_Count,Rate per sqft,Status,Property Type,Locality,Builder Name,RERA Approval,Socity,Company Name,Flat Type
0,1091,37800000,3,34678,Under Construction,3 BHK Apartment in Godrej Aristocrat,Sector 49,ETHOS PRO REALTORS,Approved by RERA,Godrej Aristocrat,Godrej,Apartment
1,1002,34700000,3,34665,Under Construction,3 BHK Apartment in Godrej Aristocrat,Sector 49,ETHOS PRO REALTORS,Approved by RERA,Godrej Aristocrat,Godrej,Apartment
2,1795,37600000,3,21000,Under Construction,3 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
3,1795,37600000,3,21000,Under Construction,3 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
4,2248,47200000,4,21000,Under Construction,4 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...
15574,1200,6000000,3,5000,Ready to move,3 BHK Apartment in Tanishq Homes Sec 105,Sector 105,seller,Not approved by RERA,Tanishq Homes Sec 105,Tanishq,Apartment
15575,2510,48000000,4,19124,Under Construction,4 BHK Apartment in M3M M3M Crown,Sector 111,home,Approved by RERA,M3M M3M Crown,M3M,Apartment
15576,1405,25200000,3,18000,Under Construction,3 BHK Apartment in Puri Diplomatic Residences,Sector 111,Property In Gurgaon,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment
15577,1981,35600000,4,18001,Under Construction,4 BHK Apartment in Puri Diplomatic Residences,Sector 111,properties for sale in Gurgaon,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment
15578,1324,23800000,3,18008,Under Construction,3 BHK Apartment in Puri Diplomatic Residences,Sector 111,PROPCURIUSE LANDBASE PVT LTD,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment

Area               int64
Price              int64
BHK_Count          int64
Rate per sqft    float64
Status            object
Property Type     object
Locality          object
Builder Name      object
RERA Approval     object
Socity            object
Company Name      object
Flat Type         object
dtype: object

In [83]:
x

0        37800000
1        34700000
2        37600000
3        37600000
4        47200000
           ...
15574     6000000
15575    48000000
15576    25200000
15577    35600000
15578    23800000
Name: Price, Length: 15579, dtype: int64

In [84]:
y

,BHK_Count,Rate per sqft,Status,Property Type,Locality,Builder Name,RERA Approval,Socity,Company Name,Flat Type
0,3,34678.0,Under Construction,3 BHK Apartment in Godrej Aristocrat,Sector 49,ETHOS PRO REALTORS,Approved by RERA,Godrej Aristocrat,Godrej,Apartment
1,3,34665.0,Under Construction,3 BHK Apartment in Godrej Aristocrat,Sector 49,ETHOS PRO REALTORS,Approved by RERA,Godrej Aristocrat,Godrej,Apartment
2,3,21000.0,Under Construction,3 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
3,3,21000.0,Under Construction,3 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
4,4,21000.0,Under Construction,4 BHK Apartment in M3M M3M Crown,Sector 111,ETHOS PRO REALTORS,Approved by RERA,M3M M3M Crown,M3M,Apartment
...,...,...,...,...,...,...,...,...,...,...
15574,3,5000.0,Ready to move,3 BHK Apartment in Tanishq Homes Sec 105,Sector 105,seller,Not approved by RERA,Tanishq Homes Sec 105,Tanishq,Apartment
15575,4,19124.0,Under Construction,4 BHK Apartment in M3M M3M Crown,Sector 111,home,Approved by RERA,M3M M3M Crown,M3M,Apartment
15576,3,18000.0,Under Construction,3 BHK Apartment in Puri Diplomatic Residences,Sector 111,Property In Gurgaon,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment
15577,4,18001.0,Under Construction,4 BHK Apartment in Puri Diplomatic Residences,Sector 111,properties for sale in Gurgaon,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment
15578,3,18008.0,Under Construction,3 BHK Apartment in Puri Diplomatic Residences,Sector 111,PROPCURIUSE LANDBASE PVT LTD,Approved by RERA,Puri Diplomatic Residences,Puri,Apartment

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
df.dtypes